<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>KeyEngine</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>KeyEngine Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ENABLE_EDITOR;WARN_MEMORY_LEAKS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);WARN_MEMORY_LEAKS;ENABLE_EDITOR</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Serialization\SceneSerialization.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="KeyEngine Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FreeTypeSharp" Version="3.0.1" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
    <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\External\VelcroPhysics\VelcroPhysics.csproj" />
  </ItemGroup>

</Project>
